### PR TITLE
updated signer, provider to state. shows a button to download metamas…

### PR DESCRIPTION
**Pull request by mhmulford0**
updated signer, provider to state. shows a button to download MetaMask if no provider found

### CODE REVIEW

**Comment by mgrillo75** [comment]
Hey man thank you!  This is my first time using Gitcoin and I am also fairly new to Github....I actually already had someone work on this issue but I will still pay you as well.  I think your solution might be better actually.  I need to figure out how to close the bounty/issue.

**Comment by mhmulford0** [comment]
Yeah if you could do it on gitcoin, that would be great! I'm trying to build up my profile.

Thank you!

**Comment by mgrillo75** [comment]
> Yeah if you could do it on gitcoin, that would be great! I'm trying to build up my profile.
> 
> Thank you!

definitely, but actually I am going to open a new bounty and will set it to approve so that I will make sure you get it.  I don't know how to pay two people for 1 bounty and I am trying to close that other one.  Ill pay you the 3.5 XTZ + the work I am requesting with the new bounty.

**Comment by mhmulford0** [comment]
I am good with React, Typescript/JavaScript, and smart contracts. I'm currently employed as a full stack web developer, so any API type stuff is good as well.

**Comment by mgrillo75** [comment]
> I look forward to it. You can reach me directly at [mhmulford0@gmail.com](mailto:mhmulford0@gmail.com) as well

are you familiar with NFTs, OpenSea, ERC-20 vs ERC-1155, etc?

**Review by mgrillo75 — APPROVED** [review]

**Comment by mhmulford0** [comment]
I am very strong on the front end so that will be a good fit. I started out about a year and a half ago now doing regular web2 stuff. I have had some Bitcoin for a while but only recently got into interacting with crypto with code. I totally agree about the money in it. Not to mention how interesting in general the space is.

**Comment by mgrillo75** [comment]
> I am very strong on the front end so that will be a good fit. I started out about a year and a half ago now doing regular web2 stuff. I have had some Bitcoin for a while but only recently got into interacting with crypto with code. I totally agree about the money in it. Not to mention how interesting in general the space is.

cool....I think I was able to just directly send you an invite to the new bounty....you won't have to write any code for this etc, it's more so I can pay you for the last one and ask you some questions about the opensea API.

**Comment by mhmulford0** [comment]
It didn't send it to me directly, but I see it posted.

**Pull request merged**
